Teguh Dwi Cahya Kusuma / 2000016015 / B

## Percobaan

Matrik dengan library NumPy

In [91]:
#NumPy
import numpy as np
matr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


Matrik dengan perulangan

In [92]:
matr1=[[a for y in range(10)] for x in range(4)]
matr1

[[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
 [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
 [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
 [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]]

Matrik 0

In [93]:
matr2=np.zeros((2,15))
print(matr2)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Matriks Random 

In [94]:
np.random.rand(2,4)

array([[0.65961753, 0.11675547, 0.66141763, 0.61445032],
       [0.53625449, 0.5303011 , 0.97514755, 0.9433253 ]])

Pemanggilan matriks

In [95]:
matr3=np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])
print('The choosen One, is you:',matr3[1][1])

The choosen One, is you: 5


Penumlahan matriks

In [96]:
ma1=[[2,5,3],
     [1,7,2],
     [3,5,0]]

ma2=[[6,4,2],
     [7,5,9],
     [0,0,1]]

for x in range(0,len(ma1)):
    for y in range(0,len(ma1[0])):
        print(ma1[x][y] + ma2[x][y],end=' ')
    print()

8 9 5 
8 12 11 
3 5 1 


Perkalian matriks

In [97]:
ma1=[[2,5,3],
     [1,7,2],
     [3,5,0]]

ma2=[[6,4,2],
     [7,5,9],
     [0,0,1]]

ma3=[]
#perkalian
for x in range(0,len(ma1)):
    row=[]
    for y in range (0,len(ma1)):
        total=0
        for z in range(0,len(ma1)):
            total=total+(ma1[x][z]*ma2[z][y])
        row.append(total)
    ma3.append(row)

#Display
for x in range(0,len(ma3)):
    for y in range(0,len(ma3[0])):
        print(ma3[x][y],end=' ')
    print()

47 33 52 
55 39 67 
53 37 51 


Transpose Determinan

In [98]:
matr4=np.array([[6,4,2],
                [7,5,9],
                [0,0,1]])
print('Sebelum urut: \n',matr4,'\nSesudah urut :\n',matr4.T)


Sebelum urut: 
 [[6 4 2]
 [7 5 9]
 [0 0 1]] 
Sesudah urut :
 [[6 7 0]
 [4 5 0]
 [2 9 1]]


Nmin, Nmax, rata-rata, varian, dan standar deviasi 

In [99]:
matr5=np.array([[9,2,5],
       [1,7,1],
       [3,5,-6]])

print('Matriks\n',matr5,'\nNilai max\n',np.max(matr5),'\nNilai min\n',np.min(matr5),'\nStandar Dev\n', round(np.std(matr5),2),'\nRata Rata\n',np.mean(matr5),'\nVarian/Ragam\n',round(np.var(matr5),2))

Matriks
 [[ 9  2  5]
 [ 1  7  1]
 [ 3  5 -6]] 
Nilai max
 9 
Nilai min
 -6 
Standar Dev
 4.08 
Rata Rata
 3.0 
Varian/Ragam
 16.67


## Tugas

### Data Matriks

In [2]:
#Run terlebih dahulu cell matriks ini, agar command yang ada dibawahnya dapat di proses
mat=[[5,0,8],
     [2,6,7],
     [1,3,4]]

### Nomor 1

In [3]:
print(mat[1][1])

6


### Nomor 2

In [4]:
print(mat[1][2])

7


### Nomor 3

In [5]:
print('Cara 1=',mat[2])

#atau

for a in range(2,len(mat)):
    print('Cara 2',end='= ')
    for b in range(len(mat)):
        print(mat[a][b],end=' ')
    print()

Cara 1= [1, 3, 4]
Cara 2= 1 3 4 


### Nomor 4

In [6]:
print('Cara 1=',[baris[0] for baris in mat])

#atau

print('Cara 2=',end=' ')
for a in range(len(mat)):
    for b in range(len(mat)-2):
        print(mat[a][b],end=' ')

Cara 1= [5, 2, 1]
Cara 2= 5 2 1 